// Code generated by qtc from "chat.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/chat.html:1
package views

//line views/chat.html:1
import (
	"strconv"

	"github.com/Jiang-Gianni/chat/message"

//line views/chat.html:2
	"github.com/Jiang-Gianni/chat/room"

//line views/chat.html:3
	"github.com/Jiang-Gianni/chat/config"
	//line views/chat.html:4
)

//line views/chat.html:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/chat.html:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/chat.html:6
func StreamChatPage(qw422016 *qt422016.Writer, rooms []room.Room, roomID int) {
//line views/chat.html:6
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat</title>
    `)
//line views/chat.html:14
	qw422016.N().S(CommonImport())
//line views/chat.html:14
	qw422016.N().S(`
    <style>
        body {
            margin: 0;
            display: flex;
            height: 100vh;
        }

        #side-menu {
            width: 15%;
            background-color: #31a2be;
        }

        #chat-container {
            flex: 1;
            overflow-y: auto;
            padding: 20px;
        }

        .room {
            padding: 0.75rem;
            margin-left: 0.25rem;
            margin-right: 0.25rem;
        }

        .room:hover {
            cursor: pointer;
            background-color: teal;
        }
    </style>
</head>

<body un-cloak>


    <div id="discard"></div>

    <dialog id="new-room">
        <article>
            <hgroup>
                <h1>New Room</h1>
                <h2>Enter a name for the room to chat</h2>
            </hgroup>
            <input type="text" name="room-name" placeholder="Room Name" aria-label="RoomName" required />
            <footer>
                <a href="#cancel" role="button" class="secondary" data-target="new-room"
                    onclick="toggleModal(event)">Cancel</a>
                <a href="#confirm" role="button" data-target="new-room" onclick="toggleModal(event)" hx-post=`)
//line views/chat.html:62
	qw422016.E().S(config.RoomEndpoint)
//line views/chat.html:62
	qw422016.N().S(` hx-target="#new-room-error" hx-include="[name='room-name']"
                    hx-swap="innerHTML">Confirm</a>
            </footer>
        </article>
    </dialog>


    <!-- <div id="sse"></div>
    <div hx-ext="sse" sse-connect="/sse" sse-swap="message" hx-target="#sse" hx-swap="afterbegin">
        Contents of this box will be updated in real time
        with every SSE message received from the chatroom.
    </div> -->

    `)
//line views/chat.html:76
	var activeRoom room.Room

//line views/chat.html:77
	qw422016.N().S(`

    <div id="side-menu" class="text-center">
        <article class="room bg-white text-black" data-target="new-room" onclick="toggleModal(event)">
            New Room
            <div id="new-room-error"></div>
        </article>
        `)
//line views/chat.html:84
	for i := range rooms {
//line views/chat.html:84
		qw422016.N().S(`
        `)
//line views/chat.html:85
		if int(rooms[i].ID) == roomID {
//line views/chat.html:85
			activeRoom = rooms[i]

//line views/chat.html:85
			qw422016.N().S(`
        <article class="room bg-blue-900 outline">`)
//line views/chat.html:86
			qw422016.E().S(rooms[i].Name)
//line views/chat.html:86
			qw422016.N().S(`</article>
        `)
//line views/chat.html:87
		} else {
//line views/chat.html:87
			qw422016.N().S(`
        <article class="room" hx-get="`)
//line views/chat.html:88
			qw422016.E().S(config.ChatRedirectRoomIDEndpoint(int(rooms[i].ID)))
//line views/chat.html:88
			qw422016.N().S(`">`)
//line views/chat.html:88
			qw422016.E().S(rooms[i].Name)
//line views/chat.html:88
			qw422016.N().S(`
        </article>
        `)
//line views/chat.html:90
		}
//line views/chat.html:90
		qw422016.N().S(`
        `)
//line views/chat.html:91
	}
//line views/chat.html:91
	qw422016.N().S(`
    </div>

    `)
//line views/chat.html:94
	if activeRoom.ID > 0 {
//line views/chat.html:94
		qw422016.N().S(`
    <div id="chat-container">
        <h2>`)
//line views/chat.html:96
		qw422016.E().S(activeRoom.Name)
//line views/chat.html:96
		qw422016.N().S(`</h2>

        <div id="message-list">
            <div id="new-message"></div>
        </div>

        <div hx-ext="ws" ws-connect="/chat/`)
//line views/chat.html:102
		qw422016.E().S(strconv.Itoa(int(activeRoom.ID)))
//line views/chat.html:102
		qw422016.N().S(`/ws">
            <div id="notifications"></div>
            `)
//line views/chat.html:104
		qw422016.N().S(ChatInput())
//line views/chat.html:104
		qw422016.N().S(`
        </div>

    </div>
    `)
//line views/chat.html:108
	}
//line views/chat.html:108
	qw422016.N().S(`

</body>

</html>
`)
//line views/chat.html:113
}

//line views/chat.html:113
func WriteChatPage(qq422016 qtio422016.Writer, rooms []room.Room, roomID int) {
//line views/chat.html:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:113
	StreamChatPage(qw422016, rooms, roomID)
//line views/chat.html:113
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:113
}

//line views/chat.html:113
func ChatPage(rooms []room.Room, roomID int) string {
//line views/chat.html:113
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:113
	WriteChatPage(qb422016, rooms, roomID)
//line views/chat.html:113
	qs422016 := string(qb422016.B)
//line views/chat.html:113
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:113
	return qs422016
//line views/chat.html:113
}

//line views/chat.html:115
func StreamNewMessage(qw422016 *qt422016.Writer, msg message.Message) {
//line views/chat.html:115
	qw422016.N().S(`
<div id="new-message" hx-swap-oob="beforebegin">
    <div class="message">`)
//line views/chat.html:117
	qw422016.E().S(msg.Username)
//line views/chat.html:117
	qw422016.N().S(`: `)
//line views/chat.html:117
	qw422016.E().S(msg.Message)
//line views/chat.html:117
	qw422016.N().S(`</div>
</div>
`)
//line views/chat.html:119
	qw422016.N().S(ChatInput())
//line views/chat.html:119
	qw422016.N().S(`
`)
//line views/chat.html:120
}

//line views/chat.html:120
func WriteNewMessage(qq422016 qtio422016.Writer, msg message.Message) {
//line views/chat.html:120
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:120
	StreamNewMessage(qw422016, msg)
//line views/chat.html:120
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:120
}

//line views/chat.html:120
func NewMessage(msg message.Message) string {
//line views/chat.html:120
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:120
	WriteNewMessage(qb422016, msg)
//line views/chat.html:120
	qs422016 := string(qb422016.B)
//line views/chat.html:120
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:120
	return qs422016
//line views/chat.html:120
}

//line views/chat.html:122
func StreamChatInput(qw422016 *qt422016.Writer) {
//line views/chat.html:122
	qw422016.N().S(`
<form id="form" ws-send>
    <input name="message" autofocus>
</form>
`)
//line views/chat.html:126
}

//line views/chat.html:126
func WriteChatInput(qq422016 qtio422016.Writer) {
//line views/chat.html:126
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:126
	StreamChatInput(qw422016)
//line views/chat.html:126
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:126
}

//line views/chat.html:126
func ChatInput() string {
//line views/chat.html:126
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:126
	WriteChatInput(qb422016)
//line views/chat.html:126
	qs422016 := string(qb422016.B)
//line views/chat.html:126
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:126
	return qs422016
//line views/chat.html:126
}

//line views/chat.html:129
func StreamNewChatError(qw422016 *qt422016.Writer, text string) {
//line views/chat.html:129
	qw422016.N().S(`
<small hx-get="`)
//line views/chat.html:130
	qw422016.E().S(config.DiscardEndpoint)
//line views/chat.html:130
	qw422016.N().S(`" class="text-red-700" hx-trigger="load delay:5s" hx-swap="outerHTML">`)
//line views/chat.html:131
	qw422016.E().S(text)
//line views/chat.html:131
	qw422016.N().S(`</small>
`)
//line views/chat.html:132
}

//line views/chat.html:132
func WriteNewChatError(qq422016 qtio422016.Writer, text string) {
//line views/chat.html:132
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:132
	StreamNewChatError(qw422016, text)
//line views/chat.html:132
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:132
}

//line views/chat.html:132
func NewChatError(text string) string {
//line views/chat.html:132
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:132
	WriteNewChatError(qb422016, text)
//line views/chat.html:132
	qs422016 := string(qb422016.B)
//line views/chat.html:132
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:132
	return qs422016
//line views/chat.html:132
}

//line views/chat.html:135
func StreamSSEMessage(qw422016 *qt422016.Writer) {
//line views/chat.html:135
	qw422016.N().S(`<div>Hello there</div>

`)
//line views/chat.html:137
}

//line views/chat.html:137
func WriteSSEMessage(qq422016 qtio422016.Writer) {
//line views/chat.html:137
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:137
	StreamSSEMessage(qw422016)
//line views/chat.html:137
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:137
}

//line views/chat.html:137
func SSEMessage() string {
//line views/chat.html:137
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:137
	WriteSSEMessage(qb422016)
//line views/chat.html:137
	qs422016 := string(qb422016.B)
//line views/chat.html:137
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:137
	return qs422016
//line views/chat.html:137
}

//line views/chat.html:138
func StreamSSEMessage2(qw422016 *qt422016.Writer) {
//line views/chat.html:138
	qw422016.N().S(`<div>Hello there</div>`)
//line views/chat.html:138
}

//line views/chat.html:138
func WriteSSEMessage2(qq422016 qtio422016.Writer) {
//line views/chat.html:138
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/chat.html:138
	StreamSSEMessage2(qw422016)
//line views/chat.html:138
	qt422016.ReleaseWriter(qw422016)
//line views/chat.html:138
}

//line views/chat.html:138
func SSEMessage2() string {
//line views/chat.html:138
	qb422016 := qt422016.AcquireByteBuffer()
//line views/chat.html:138
	WriteSSEMessage2(qb422016)
//line views/chat.html:138
	qs422016 := string(qb422016.B)
//line views/chat.html:138
	qt422016.ReleaseByteBuffer(qb422016)
//line views/chat.html:138
	return qs422016
//line views/chat.html:138
}
