// Code generated by qtc from "denied.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/denied.html:1
package views

//line views/denied.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/denied.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/denied.html:1
func StreamDeniedPage(qw422016 *qt422016.Writer) {
//line views/denied.html:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>

<head>
    <title>Access Denied</title>
    <meta charset="utf-8">
    <meta name="description" content="Meta Description">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    `)
//line views/denied.html:11
	qw422016.N().S(CommonImport())
//line views/denied.html:11
	qw422016.N().S(`
</head>

<body un-cloak>
    <main class="container flex-row">
        <article class="grid">
            <div>
                <hgroup>
                    <h1>Access Denied</h1>
                    <h2>Your access was denied because you are not authenticated or you don't have the right permissions
                    </h2>
                </hgroup>
                <div class="text-center">
                    <strong>
                        <a href="/">Return to Login</a>
                    </strong>


                    <ins id="error" hidden></ins>

                </div>
            </div>
        </article>

    </main>
</body>

</html>
`)
//line views/denied.html:39
}

//line views/denied.html:39
func WriteDeniedPage(qq422016 qtio422016.Writer) {
//line views/denied.html:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/denied.html:39
	StreamDeniedPage(qw422016)
//line views/denied.html:39
	qt422016.ReleaseWriter(qw422016)
//line views/denied.html:39
}

//line views/denied.html:39
func DeniedPage() string {
//line views/denied.html:39
	qb422016 := qt422016.AcquireByteBuffer()
//line views/denied.html:39
	WriteDeniedPage(qb422016)
//line views/denied.html:39
	qs422016 := string(qb422016.B)
//line views/denied.html:39
	qt422016.ReleaseByteBuffer(qb422016)
//line views/denied.html:39
	return qs422016
//line views/denied.html:39
}
