// Code generated by qtc from "login.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/login.html:1
package views

//line views/login.html:1
import "github.com/Jiang-Gianni/chat/config"

//line views/login.html:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/login.html:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/login.html:2
func StreamLoginPage(qw422016 *qt422016.Writer) {
//line views/login.html:2
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Meta Description">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    `)
//line views/login.html:12
	qw422016.N().S(CommonImport())
//line views/login.html:12
	qw422016.N().S(`
</head>

<body>
    <main class="container flex-row">
        <article class="grid">
            <div>
                <hgroup>
                    <h1>Log in or Register</h1>
                    <h2>Enter your username and password</h2>
                </hgroup>
                <div class="text-center">
                    <input type="text" name="username" placeholder="Username" aria-label="Username" required />
                    <input type="password" name="password" placeholder="Password" aria-label="Password" required />

                    <button type="submit" class="primary" hx-post="`)
//line views/login.html:27
	qw422016.E().S(config.LoginEndpoint)
//line views/login.html:27
	qw422016.N().S(`"
                        hx-include="[name='username'],[name='password']" hx-target="#error">Login</button>

                    <button type="submit" class="contrast" hx-post="`)
//line views/login.html:30
	qw422016.E().S(config.RegisterEndpoint)
//line views/login.html:30
	qw422016.N().S(`"
                        hx-include="[name='username'],[name='password']" hx-target="#error">Register</button>

                    <ins id="error" hidden></ins>

                </div>
            </div>
        </article>

    </main>
</body>

</html>

`)
//line views/login.html:44
}

//line views/login.html:44
func WriteLoginPage(qq422016 qtio422016.Writer) {
//line views/login.html:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/login.html:44
	StreamLoginPage(qw422016)
//line views/login.html:44
	qt422016.ReleaseWriter(qw422016)
//line views/login.html:44
}

//line views/login.html:44
func LoginPage() string {
//line views/login.html:44
	qb422016 := qt422016.AcquireByteBuffer()
//line views/login.html:44
	WriteLoginPage(qb422016)
//line views/login.html:44
	qs422016 := string(qb422016.B)
//line views/login.html:44
	qt422016.ReleaseByteBuffer(qb422016)
//line views/login.html:44
	return qs422016
//line views/login.html:44
}

//line views/login.html:46
func StreamLoginRegisterError(qw422016 *qt422016.Writer, text string) {
//line views/login.html:46
	qw422016.N().S(`
<strong id="error" class="contrast" hx-swap-oob="true">`)
//line views/login.html:47
	qw422016.E().S(text)
//line views/login.html:47
	qw422016.N().S(`</strong>
`)
//line views/login.html:48
}

//line views/login.html:48
func WriteLoginRegisterError(qq422016 qtio422016.Writer, text string) {
//line views/login.html:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/login.html:48
	StreamLoginRegisterError(qw422016, text)
//line views/login.html:48
	qt422016.ReleaseWriter(qw422016)
//line views/login.html:48
}

//line views/login.html:48
func LoginRegisterError(text string) string {
//line views/login.html:48
	qb422016 := qt422016.AcquireByteBuffer()
//line views/login.html:48
	WriteLoginRegisterError(qb422016, text)
//line views/login.html:48
	qs422016 := string(qb422016.B)
//line views/login.html:48
	qt422016.ReleaseByteBuffer(qb422016)
//line views/login.html:48
	return qs422016
//line views/login.html:48
}
