// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package room

import (
	"context"
)

type Querier interface {
	GetRooms(ctx context.Context) ([]Room, error)
	InsertRoom(ctx context.Context, roomName string) (int64, error)
}

var _ Querier = (*Queries)(nil)
