// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package user

type User struct {
	ID         int64  `json:"id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	LastRoomID int64  `json:"last_room_id"`
}
