// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package user

import (
	"context"
)

type Querier interface {
	CountUser(ctx context.Context, username string) (int64, error)
	GetUser(ctx context.Context, username string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
