direction:right
Room A {
    Client A
    Client B
}

Room B{
    Client C
}

WebService{
    Connection A
    Connection B
    Connection C
}

MessageService{
    Stream A
    Stream B
    Stream C
}

Room A.Client A -> WebService.Connection A: WebSocket, Message from A (1)
Room A.Client B -- WebService.Connection B: WebSocket
Room B.Client C -- WebService.Connection C: WebSocket

WebService.Connection A -> MessageService.Stream A: gRPC, Message from A (2)
WebService.Connection B -- MessageService.Stream B: gRPC
WebService.Connection C -- MessageService.Stream C: gRPC

DB

MessageService -> DB: Store Message from A (3)

MessageService.Stream A -> WebService.Connection A: Message to Room A Conns (4)
MessageService.Stream B -> WebService.Connection B: Message to Room A Conns (4)

WebService.Connection A -> Room A.Client A: Message to Room A Clients (5)
WebService.Connection B -> Room A.Client B: Message to Room A Clients (5)
