title: NATS {
  shape: text
  near: top-center
  style: {
    font-size: 55
  }
}

Frontend{
    htmx:""{
        shape: image
        icon: ./img/htmx.png
    }
}

DB{
    near: bottom-center
    shape:cylinder
    SQLite:""{
        shape: image
        icon: ./img/sqlite.png
    }
}

NATS:{
    shape:queue
    NATS_img:""{
        shape: image
        icon: ./img/NATS.png
        width: 400
        height: 100
    }
}

WebService{
    Go:""{
        shape:image
        icon: ./img/gopher.png
    }
}

UserService{
    Go:""{
        shape:image
        icon: ./img/gopher.png
    }
}

MessageService{
    Go:""{
        shape:image
        icon: ./img/gopher.png
    }
}

RoomService{
    Go:""{
        shape:image
        icon: ./img/gopher.png
    }
}

Frontend -- WebService: WebSocket
Frontend -- WebService: HTTP

WebService -- NATS: tcp ip

NATS -- UserService: tcp ip
NATS -- RoomService: tcp ip
NATS -- MessageService: tcp ip

UserService -- DB
RoomService -- DB
MessageService -- DB